### ISSUE TITLE
Some Pleiades identifiers are not IRIs (Turtle and SPARQL standards compliance)

### ISSUE THREAD

**Issue by wouterbeek** [isawnyu/pleiades-rdf#6]
Hi,

First of all: thanks for putting this interesting Linked Data project online!

I was playing around with the data a bit and had some problems loading and querying it.
The culprit of these problems is that some of the resource identifiers that Pleiades uses are not IRIs but URI references.

For example the following triple in data dump file `places-7.ttl` (last character of the subject term):

```
<http://atlantides.org/capgrids/79#A2 > osgeo:extent <http://atlantides.org/capgrids/79#A2 -extent> .
```

This means that the data is valid RDF data (which required URI references) but cannot be queried using SPARQL (see both the SPARQL 1.0 specification http://www.w3.org/TR/rdf-sparql-query/#QSynIRI and the SPARQL 1.1 specification http://www.w3.org/TR/2013/REC-sparql11-query-20130321/#QSynIRI).

The RDF data dumps use the Turtle serialization format, but the Turtle standard also requires the use IRIs (see http://www.w3.org/TR/2013/CR-turtle-20130219/).

There may be several ways in which this might be solved. Replacing the URIs that use spaces with IRIs that do not would be one solution. Making use of percent-escaping to encode the spaces differently would be another.
Any ideas on which solution would be best?

Cheers!,
Wouter.

**Comment by paregorios** [comment]
This was resolved some time ago. See https://github.com/isawnyu/pleiades-gazetteer/issues/9#issuecomment-1073963074
