### ISSUE TITLE
Occurrence of URI scheme and host information in URI path components.

### ISSUE THREAD

**Issue by wouterbeek** [isawnyu/pleiades-rdf#7]
Hi,

Another small complaint: some URIs seem malformed, since they contain the Pleiades URI scheme and host name twice. I'm not sure whether these are valid URIs and/or IRIs, especially the colon and the double forward slash in the URI path seems non-standard, but I would have to look that up in some RFC standard.

For instance the following triple occurs in RDF data dump `places-5.ttl` (the object term):

```
<http://pleiades.stoa.org/places/55607045#this> owl:sameAs <http://pleiades.stoa.org/http://pleiades.stoa.org/places/422889#this> .
```

Do these URIs [1] denote the same object as their related URIs [2]?
If so, one might consider making the identities explicit by adding triples [3]:

```
[1] http://pleiades.stoa.org/http://pleiades.stoa.org/places/422889#this
[2] http://pleiades.stoa.org/places/422889#this
[3] <http://pleiades.stoa.org/http://pleiades.stoa.org/places/422889#this> owl:sameAs <http://pleiades.stoa.org/places/422889#this>
```

Cheers!,
Wouter.

**Comment by wouterbeek** [comment]
```
<http://www.persee.fr/web/revues/home/prescript/article/racf_0220-6617_1991_num_30_1_2657?luceneQuery=%28%2B%28content%3AAQUAE+title%3AAQUAE^2.0+fullContent%3AAQUAE^100.0+fullTitle%3AAQUAE^140.0+summary%3AAQUAE+authors%3AAQUAE^5.0+illustrations%3AAQUAE^4.0>,

**Comment by paregorios** [comment]
I've cleaned up the references in https://pleiades.stoa.org/places/109330, which gets rid of the query string components that were causing the specific example cited by @wouterbeek, above. We have an open issue on our primary tracker for the general problem of malformed URIs in our RDF output, so let's use that for further issues of this nature. https://github.com/isawnyu/pleiades-gazetteer/issues/9
